kookmin-sw/capstone-2020-12

src/server/Pipfile, src/server/Pipfile.lock, src/server/schema.graphql
This pull request closes #10
GraphQL 스키마 디자인 완료했습니다.
빠진 것 없는 지 점검해주세요.
=> GraphQL 스키마 디자인 완료

src/web/package.json, src/web/src/components/media-detail-card-query.js, src/web/src/components/media-detail-card.js, src/web/src/components/media-detail-delete-button.js, src/web/src/pages/media-detail-page.js
issue #2 #4 
Media Detail Card component UI
Media Detail delete button UI
Media Detail Page UI
=> Mediadetail UI component

src/server/app.py, src/server/mock_data.py, src/server/resolvers/__init__.py, src/server/resolvers/mutation.py, src/server/resolvers/query.py
=> feat(uploadMedia): uploadMedia mutation 구현

src/server/resolvers/mutation.py, src/server/resolvers/query.py
=> feat(delete-media): deleteMedia mutation 구현

src/web/src/components/media-detail-card-query.js, src/web/src/components/media-detail-card.js, src/web/src/components/media-detail-delete-button.js, src/web/src/pages/media-detail-page.js
=> media detail query 구현

src/web/src/components/SearchBarSubmitButton.js
query parameter적용했고 url, query보내고 받는거까지 확인 완료
=> query parameter 적용

src/web/src/components/error-view.js, src/web/src/components/media-detail-card-query.js, src/web/src/components/media-detail-delete-button.js, src/web/src/pages/media-detail-page.js, src/web/src/pages/media-view-page.js
issue #21 
- Web에서 미디어를 삭제하는 기능 구현
- 미디어를 삭제하고 나서 user 페이지로 redirect
- Media Detail page로 갈 때, error가 난다면 이전 페이지로 redirect
=> web Media delete 기능 구현

src/web/src/components/MediaList/MediaCard.js, src/web/src/pages/MediaListPage.js
- 쿼리와 카드 컴포넌트를 분리하지 못하고 한 페이지에 몰아서 가독성이 떨어질 수 있습니다.
- mediaID 전달이 정확하게 되는지 확인하지 못했습니다.
완벽하지 않아서 죄송합니다ㅠㅠ
=> upload pages/MediaListPage.js

src/web/src/pages/media-view-page.js
=> layout center로 변경

src/server/resolvers/mutation.py, src/server/schema.graphql
1. 미디어 변환 및 업로드 작업이 진행중인지를 나타내는 isProcessing 추가. 임시 방편으로 영상이 업로드되면 무조건 isProcessing 이 True 이다. False 로 바뀌지 않는다. 추후 미디어 품질 향상 모듈의 제작이 완료되면 수정 필요.
2. 업로드 시 임시 유저 정보 추가
=> isProcessing 추가 & 업로드 시 임시 유저 정보 추가 

src/server/app.py, src/server/mock_data.py, src/server/resolvers/mutation.py, src/server/resolvers/query.py, src/server/resolvers/video.py, src/server/schema.graphql
이 pull request는 프론트의 변경이 요구됩니다.
**꼭 확인하세요**
1. date정보가 삭제되고 year로 통일함에 따라 스키마에 변경이 있습니다.
2. search에 년도 기반 필터링이 구현되었습니다.
3. isProcessing 을 가져올 때 발생하는 버그를 수정하였습니다.
=> 베타 요구사항 반영

src/web/src/components/Media/media-detail-card.js, src/web/src/pages/upload-page.js
* media-detail-card 을 function 으로 바꿈
=> function으로 바꾸고 빈칸 삭제

src/web/src/App.js, src/web/src/components/Header/header-icons-loginButton.js, src/web/src/components/Header/header-icons-uploadButton.js, src/web/src/components/Header/header-icons-userMenu.js, src/web/src/components/Header/header-icons.js, src/web/src/components/Header/header.js, src/web/src/components/Media/media-detail-card-query.js, src/web/src/pages/login-page.js, src/web/src/pages/media-view-page.js, src/web/src/pages/register-page.js
5.8 금요일에 회의에서 나온 피드백 반영
1. login 버튼 디자인 변경
2. 로그인 했을 때 youtube처럼 user페이지와 로그인 버튼을 한 곳에 모아둠
3. alert사용 대신 antd의 message 사용
* 형이 지적했던 client부분은 계속 시도중인데 아직 성공을 못해서;; issue에 올려놓고 공부 좀 하면서 고치겠습니다.
* 색이나 디자인 마음에 안드시는 부분은 따로 말씀해 주세요. 우선 슬랙에 보낸 디자인으로 pull request 보냅니다.
=> V1.0 login

src/web/src/App.js, src/web/src/components/Header/header-icons-userMenu.js, src/web/src/components/Media/media-list.js, src/web/src/components/Media/media-search-query.js, src/web/src/pages/home-page.js, src/web/src/pages/media-list-page.js, src/web/src/pages/user-page.js
우선 기능만 적용, 디자인 수정 필요
로그아웃시 홈 화면으로 이동하지 않던 문제 해결
media-list를 재사용하기 위해서 component 나눔
=> V1.0 user page

src/web/src/components/Header/header-icons-userMenu.js, src/web/src/pages/media-view-page.js, src/web/src/pages/user-page.js
1. user page로 이동시 network에러 발생 문제 해결
2. 미디어 리스트의 원소가 1개일 때 미디어 이동 버튼 사용 불가 설정
3. Popover에서 내 채널을 눌렀을 때 PopOver가 닫히지 않던 문제 해결
=> V1.0 update

src/web/src/components/Header/header-icons-uploadButton.js, src/web/src/components/Header/header-icons.js, src/web/src/components/Header/header.js, src/web/src/components/Media/media-card.js, src/web/src/components/SearchBar/search-bar.js
1. Media card 테두리 둥근 사각형 적용
2. Navbar 수정(Logo, Searchbar, Buttons)
=> V1.0 responsive

src/web/.eslintrc.json, src/web/src/App.js, src/web/src/components/Media/media-detail-card.js, src/web/src/components/UploadPage/dropzone-box.js, src/web/src/components/UploadPage/upload-category-select.js, src/web/src/components/UploadPage/upload-submit-button.js, src/web/src/components/constants.js, src/web/src/pages/home-page.js, src/web/src/pages/login-page.js, src/web/src/pages/upload-page.js
=> upload error 해결

src/server/README.md, src/server/data-sources.js, src/server/docker-compose.yml, src/server/resolvers/mutation.js, src/server/schema.js, src/web/src/components/Media/media-detail-delete-button.js, src/web/src/components/UserPage/user-media-deleteButton.js
미디어와 댓글 수정 기능을 구현했습니다.
'이'가 붙어야하는 경우가 일반적으로 더 많아서 미디어 삭제 메시지도 살짝 수정했습니다. ~가(이) 삭제되었습니다. => ~이(가) 삭제되었습니다.
=> modifyComment, modifyMedia mutation구현

src/server/data-sources.js, src/server/migrations/20201009173516_rename_body_to_content.js, src/server/resolvers/comment.js, src/server/resolvers/mutation.js, src/server/schema.js, src/server/seeds/mock_data.js, src/web/src/components/Media/MediaComment/media-add-comment.js, src/web/src/components/Media/MediaComment/media-comment-list.js, src/web/src/components/Media/MediaComment/media-comment.js, src/web/src/components/Media/MediaComment/media-delete-comment.js, src/web/src/components/Media/MediaComment/media-modify-comment.js
This PR closes #155 
- comment의 body를 content로 바꿈
=> Refactor(server) re naming #155

.editorconfig
Hey again, this should work now, it's JUST the .editorconfig file and I did test it with various files.  I don't know what happened the last time but this should be much much better now.  Sorry for inconvenience my last pull request did.
=> Issue #136-Just .editorconfig now

src/server/media_enhancement_module/app.py
Change Status code to defined variable
Divide functions in multiple lines
closes #161
=> refactor: Remove redundant code

src/server/media_enhancement_module/image_colorization_module/app.py, src/server/media_enhancement_module/image_super_resolution_module/app.py, src/server/media_enhancement_module/research/colorization/main_whole_up.py, src/server/media_enhancement_module/research/colorization/myflowlib_up.py, src/server/media_enhancement_module/research/colorization/preprocess/change_conv2d.py, src/server/media_enhancement_module/research/colorization/preprocess/video_resolution.py, src/server/media_enhancement_module/research/colorization/pytorch_pwc/flowlib.py, src/server/media_enhancement_module/research/colorization/pytorch_pwc/run.py, src/server/media_enhancement_module/research/colorization/pytorch_pwc/run_data.py, src/server/media_enhancement_module/research/colorization/utils_up.py, src/server/media_enhancement_module/video_colorization_module/app.py, src/server/media_enhancement_module/video_preprocessing_module/app.py, src/server/media_enhancement_module/video_super_resolution_and_frame_interpolation_module/app.py
=> remove redundant code, remove flag variable and change request code

src/server/resolvers/constants.js, src/server/resolvers/enums.js, src/server/resolvers/media.js, src/server/resolvers/mutation.js
This PR closes #158 
- constants.js 파일을 추가하여 상수 값을 추가함
- 기존에는 string으로 IMAGE와 VIDEO를 구별 -> `types.image`, `types.video` 으로 구별
=> Refactor(server) set category key based on id #158

src/server/data-sources.js, src/server/migrations/20201018184827_user_active_flag.js
- user table에 is_active column을 추가하기 위해 data migration file 추가
- data-sources.js에서 user deactivation하는 함수 구현
close #153
=> Data history

src/server/data-sources.js, src/server/migrations/20201029161500_media_active_flag.js
- media DB에 isActive column 추가
- data-source의 deleteMedia 함수에서 db에서 media delete가 아닌 isActive column을 true에서  false로 update
close #176
=> Media activeflag
